version: "3"

services:
  web:
    depends_on:
      - db
    build: .
    command: gunicorn api.wsgi --bind 0.0.0.0:8000
    restart: always
    networks:
      - api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/code
    env_file:
      - .env

  nginx:
    container_name: ncp-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - api
    restart: always
    ports:
      - 80:80
    depends_on:
      - web

  db:
    build: './postgres'
    ports:
      - "5432:5432"
    networks:
      - api
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

networks:
  api:
    driver: bridge

